### ISSUE TITLE
Resolve Non-nullable Property Must Contain a Non-null Value

### ISSUE THREAD

**Issue by HumairaSid** [johnkors/aspnetcore7-compat-repro#1]
There are different ways to resolve this

You can initialize the properties
you can disable the nullable types 
or you can use the null forgiving operator like
  public string MightBeRequiredDependingOnNullabilityProp { get; set; } = null!;

**Comment by johnkors** [comment]
Yes - the issue is not with how to resolve it. That's simple. 

This repro is just showing that there are unlisted/undocumented breaking changes between 6 to 7.

This new behaviour should be documented, so one is aware of it when migrating. This hit us whilst migrating.

**Comment by HumairaSid** [comment]
If you can guide me on where to do the documentation, I can help with documenting.

**Comment by johnkors** [comment]
Microsoft is already on it, thanks.
